### ISSUE TITLE
error: format not a string literal and no format arguments when building on Ubuntu 16.04

### ISSUE THREAD

**Issue by ekisu** [cosarara97/fucking-weeb#2]
The program fails to build on Ubuntu 16.04, with the above error.

Build log:
```
csc -vk weeb.scm -C "`pkg-config --cflags gtk+-3.0`" -L "`pkg-config --libs gtk+-3.0`"
'/usr/bin/chicken' 'weeb.scm' -output-file 'weeb.c' -verbose

Warning: in toplevel procedure `set-cover':
  (weeb.scm:170) in procedure call to `append!', expected argument #1 of type `list', but was given an argument of type `undefined'
'gcc' 'weeb.c' -o 'weeb.o' -c  -fno-strict-aliasing -fwrapv -DHAVE_CHICKEN_CONFIG_H -DC_ENABLE_PTABLES -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -pthread -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/mirclient -I/usr/include/mircommon -I/usr/include/mircookie -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng12 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I"/usr/include/chicken"
weeb.c: In function ‘stub1059’:
weeb.c:882:1: error: format not a string literal and no format arguments [-Werror=format-security]
 return(gtk_message_dialog_new(a0 , a1 , a2 , a3 , a4));
 ^
cc1: some warnings being treated as errors

Error: shell command terminated with non-zero exit status 256: 'gcc' 'weeb.c' -o 'weeb.o' -c  -fno-strict-aliasing -fwrapv -DHAVE_CHICKEN_CONFIG_H -DC_ENABLE_PTABLES -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -pthread -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/mirclient -I/usr/include/mircommon -I/usr/include/mircookie -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng12 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I"/usr/include/chicken"
Makefile:14: recipe for target 'weeb' failed
make: *** [weeb] Error 1
```

**Comment by cosarara** [comment]
Fixed with https://github.com/cosarara97/fucking-weeb/pull/3
